image: php:7.2

cache:
  paths:
    - vendor/

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq

  # Install xdebug
  - pecl install xdebug && docker-php-ext-enable xdebug

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

test:
  script:
    - vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --coverage-text
