image: php:7.2

cache:
  paths:
    - vendor/

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq

  # Install xdebug
  - pecl install xdebug && docker-php-ext-enable xdebug

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --coverage-text

deploy:
  stage: deploy
  script:
    - apt-get install lftp -yqq
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rv ./ ./ --ignore-time --no-symlinks --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - master
