image: php:7.2

cache:
  paths:
    - vendor/

before_script:
  # Install git and libicu-dev (for intl) and wget (for composer-install.sh script), the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git libicu-dev wget -yqq

  # Install intl
  - docker-php-ext-install intl

  # Install composer
  - ./composer-install.sh

  # Generate *.res resource bundle files
  - genrb --verbose --destdir locale/ --encoding utf-8 locale/*.txt

stages:
  - test
  - deploy

test:
  stage: test
  script:
    # Install xdebug (for phpunit coverage)
    - pecl install xdebug && docker-php-ext-enable xdebug
    - php composer.phar test

deploy:
  stage: deploy
  script:
    - php composer.phar install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --no-suggest --optimize-autoloader
    - apt-get install lftp -yqq
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rev ./ ./proxy-bank/ --ignore-time --no-symlinks --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - master
